### ISSUE TITLE
Müller MIDI 3.0 - Sprayer doesn't start

### ISSUE THREAD

**Issue by gunicsba** [Open-Agriculture/AgIsoVirtualTerminal#25]
Hello,

I have access to a Müller / Trimble MIDI 3.0 ECU. I tried to load it into Virtual Terminal on 2 computers but failed.

There's a few warning? message:
[VT Server]: Client 135 change numeric value command: change object ID 4508 to be 0
[VT Server]: Client 135 changed object 1514 attribute 8 to 1008981770
[VT Server]: Client 135 changed object 1514 attribute 9 to 2
[VT Server]: Client 135 change numeric value command: change object ID 4514 to be 0
[VT Server]: Client 135 changed object 1502 attribute 8 to 1065353216
[VT Server]: Client 135 changed object 1502 attribute 9 to 0
[VT Server]: Client 135 change numeric value command: change object ID 4502 to be 1100
[VT Server]: Client 135 change numeric value invalid object ID of 5703
[VT Server]: Client 135 hide object command 922
[VT Server]: Client 135 change numeric value invalid object ID of 5704
[VT Server]: Client 135 hide object command 923
[VT Server]: Client 135 show object command 1206
[VT Server]: Client 135 change numeric value command: change object ID 12069 to be 65535
[VT Server]: Client 135 hide/show object command failed. It can only affect containers! ID: 60449
[VT Server]: Client 135 change soft key mask command: invalid data mask or alarm mask object ID of 42241

However there's this I assume FATAL? error:

[WS]: IOP Language parsed: tr
[WS]: IOP Language parsed: uk
[WS]: Picture graphic object has invalid dimensions compared to its data. Object: 2023
[WS]: Parsing object pool failed.
[WS]: Object pool failed to be parsed.
[VT Server]: Client 135 change attribute 3 invalid object ID of 63505

I tried en-US and hu-HU locales, but it didn't make a difference.

I'm using Peak PCAN USB hardware.

Attaching the logs generated by the software.
[AgISOVirtualTerminalLogs_30_Sep_2024_10_49_34am.zip](https://github.com/user-attachments/files/17187070/AgISOVirtualTerminalLogs_30_Sep_2024_10_49_34am.zip)

**Comment by ad3154** [comment]
Thanks for this, I will try to pull the IOP data from your logs and see if I can reconstruct the object pool to investigate

**Comment by ad3154** [comment]
This should be fixed by this pull request on the main CAN stack: https://github.com/Open-Agriculture/AgIsoStack-plus-plus/pull/497

Thanks again for pointing this out, and I would love to know if after this update your implement works OK!

**Comment by gunicsba** [comment]
I can confirm your proposed changes do help. I was able to build it myself and the main menu do loads.
I see a few issues I'll make new tickets for better tracking.
