### ISSUE TITLE
Add support for parsing UTF-16 strings

### ISSUE THREAD

**Issue by ad3154** [Open-Agriculture/AgIsoVirtualTerminal#27]
Fix TODO where currently we're just rejecting UTF-16 strings.

This should be pretty easy to add in the VT... we just need to check if it's UTF-16, and grab it with the Juce CharPointer_UTF16 or something similar.

![image](https://github.com/user-attachments/assets/b5937907-1d66-4caf-86de-d0ab7d434650)

**Comment by gunicsba** [comment]
Maybe this will fix the Hungarian accented letters as well?
This is how we usually test this:
árvíztűrő tükörfúrógép 
ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP
