### ISSUE TITLE
Configurable screen and softkey dimensions

### ISSUE THREAD

**Issue by GwnDaan** [Open-Agriculture/AgIsoVirtualTerminal#3]
Some pools only run well on certain dimensions. To aid the the compatibility and usability across various devices we should offer options for adjusting these parameters.

**Comment by JayQu9** [comment]
Although this can adjust the screen and softkey dimensions, the number of softkeys can only be displayed as 6. I think most terminals display 12，like this config
![image](https://github.com/user-attachments/assets/18404a3e-2145-4629-b49c-37a4b80c39eb)
. @ad3154

**Comment by ad3154** [comment]
> Although this can adjust the screen and softkey dimensions, the number of softkeys can only be displayed as 6. I think most terminals display 12，like this config

OK, will address in  #18 I agree most seem designed for 12 keys
